### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by noahsettersten** [headwayio/suspenders#23]
Update the suspenders references to correctly refer to `voyage` in the README and elsewhere.

Also, add instructions to create a gemset first before running voyage and change to that gemset.

**Comment by jondkinney** [comment]
@noahsettersten because we want to keep this as easy to upgrade / rebase to upstream as possible, I don't want to customize the main readme at all. The approach with this app is one of overriding their defaults by re-opening classes in our newly defined files, not directly editing any of their files (unless absolutely necessary). There is a separate voyage readme already, we can extend and enhance that. That voyage readme lists the current files that we should expect to need to resolve conflicts in based on our modification of them.

**Comment by noahsettersten** [comment]
I had incorrectly assumed that we would ignore their upstream README in retrieving updates to bring into our repo. I can migrate all of my documentation changes to our custom voyage readme that gets generated in the new app; that will avoid any issues there then.

The only drawback is that all of the documentation on the main repo page for GitHub will continue to reference Suspenders and that has been confusing in the past for anyone new on the team who doesn't realize that the main README is entirely irrelevant as far as commands and a handful of the gems listed since we've customized it for our setup. Any ideas for making that clearer for new users?

**Comment by jondkinney** [comment]
Not sure if this'll help or not: 

![image](https://user-images.githubusercontent.com/4521/31561527-c33e19ec-b01d-11e7-9383-033297218f3e.png)

Other than that, I'm not sure. I guess we should help people understand what the repo is / how we're maintaining it so they understand to ignore the main readme, mostly.

**Comment by noahsettersten** [comment]
I think that will be helpful overall. Ideally everyone will be up to speed before attempting to interpret the codebase in the repo themselves anyway.
