### ISSUE TITLE
Create rvm gemset before bundling

### ISSUE THREAD

**Issue by jason-headway** [headwayio/suspenders#24]
Bundler installs into current gemset and then creates a new gemset based on the project name.  The order of these operations should be swapped.

**Comment by noahsettersten** [comment]
@jason-headway From what I can tell, Voyage actually doesn't create or configure a gemset at all. Right now that's a pre-requisite before running Voyage at all. I'll update the documentation to make that more clear for now, and we can re-evaluate later if the new documented process has issues.

**Comment by jondkinney** [comment]
I try to be a little helpful in this regard

![image](https://user-images.githubusercontent.com/4521/31561030-32beaf2c-b01c-11e7-9c53-e869e533b007.png)

**Comment by noahsettersten** [comment]
For those with less rvm experience though, about the only giveaway today is the 'install Rails in the desired gemset' message. And if you installed the voyage gem as usual, you typically won't even see that message.

I was initially confused as well since the `bundle install` message appears to state that it will setup the app for the current gemset, but that isn't the case as it uses the app's name for the future gemset. So if you haven't already manually created a gemset and switched to it first, you'll end up with voyage installing all of the gems in the current gemset, and then switching the app to an entirely different one (that doesn't exist) based around the app name.

Ideally we'd have voyage create and then use the gemset itself, unless there are other issues or considerations there.
