### ISSUE TITLE
Make API compatible

### ISSUE THREAD

**Issue by jondkinney** [headwayio/suspenders#3]
Add Gems: 

- [x] https://github.com/gonzalo-bulnes/simple_token_authentication
- [x] https://github.com/rails-api/active_model_serializers

Look at test setup:

- [x] https://robots.thoughtbot.com/validating-json-schemas-with-an-rspec-matcher

**Comment by jondkinney** [comment]
@noahsettersten thoughts on this after running it in the context of hypremium? Is there anything we can do to automate this with a prompt up front during generation time?

**Comment by noahsettersten** [comment]
The three items you referenced would be my thoughts for API-specific changes.

I can see adding an API / token option during setup to take care of creating the necessary database migration and code changes to allow the User model to be token authenticatable. We could also add the JSON handling and tests as well.  Most of my time getting the app up and running was spent on writing RSpec/capybara tests to get code coverage up. Instead of lowering the minimum coverage needed, I took it as an opportunity to learn more of those skills.

A few other things that we may want to consider adding unrelated to the API usecase:

- Adding links for sign in / sign out to the nav header
- Move main page content inside of a div to allow for adding padding
(Both in https://github.com/headwayio/hypremium-api/commit/ea86142fa2e92a5d678c909c689a4e5c3d1e0594)

- Tweaking circle.yml to install bundler and update rubygems to handle 2.4.0, and modify the test command to generate JUnit formatted XML for Circle to get better stats on the tests run.
(See https://github.com/headwayio/hypremium-api/blob/master/circle.yml)

**Comment by noahsettersten** [comment]
Doing a recent generate from your new branch (now in master), I believe these have all been done. I'm going to hold off on adding the new 'API' setup option for a future issue to rollup jsonapi-utils and tiddle as well.
