### ISSUE TITLE
Administrate Fields should be added to end

### ISSUE THREAD

**Issue by GeekOnCoffee** [headwayio/suspenders#47]
When the dashboards are generated. Find a way to add the text we want in the appropriate place.

**Comment by noahsettersten** [comment]
@GeekOnCoffee With your latest round of changes that were merged in, I see the auto-generated fields in the user dashboard as well like you were. Something must have changed to create the user table in the database earlier on.

I'm not sure we have a good option for detecting the ends of the individual sections since they all close with the same keywords. Perhaps we could do a replace before the closing keyword and the opening one of the next section? That wouldn't work for the last section though.

**Comment by GeekOnCoffee** [comment]
@noahsettersten I did attempt that briefly, I think maybe I wasn't getting the line breaks correctly though.
